# Generated by Django 5.0.1 on 2024-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(max_length=2000, null=True, upload_to='user/'),
        ),
    ]
